In [1]:
#area of rectangle
def area_simple_multiplication(length, width):
    return length * width

length = 5
width = 8
result = area_simple_multiplication(length, width)
print(f"Area of Rectangle: {result}")


Area of Rectangle: 40


In [2]:
#miles to kilometers
# miles input from the user
miles = float(input("Enter value in miles: "))

# calculate kilometers and display
kilometers = miles * 1.60934
print('%0.3f miles is equal to %0.3f kilometers' %(miles, kilometers))

Enter value in miles: 70
70.000 miles is equal to 112.654 kilometers


In [3]:
#string  is a palindrome

def is_palindrome(s: str) -> bool:
    return s == s[::-1]

input_string = "malayalam"
if is_palindrome(input_string):
    print("Yes")
else:
    print("No")

Yes


In [4]:
#finding second largest number
def find_second_largest_sorted(arr):
    unique_list = list(set(arr))
    unique_list.sort()
    return unique_list[-2]

my_list = [10, 20, 4, 45, 99]
print("Second largest number is:", find_second_largest_sorted(my_list))



Second largest number is: 45


In [7]:
#indentation in python
#Indentation is a very important concept of Python because without properly indenting the Python code, you will end up seeing IndentationError and the code will not get compiled.


In [9]:
#set difference operation
# Define two sets
A = {0, 2, 4, 6, 8}
B = {1, 2, 3, 4, 5}

# Calculate the difference between sets A and B
difference_result = A - B
# Print the result
print("Difference between sets A and B:", difference_result)


Difference between sets A and B: {0, 8, 6}


In [10]:
#whileloop
print('Numbers from 1 to 10:')
n = 1
while n <= 10:
    print(n, end=' ')
    n += 1

Numbers from 1 to 10:
1 2 3 4 5 6 7 8 9 10 

In [11]:
#using if else elif
num = float(input("Enter a number: "))
if num >= 0:
    if num == 0:
        print("Zero")
    else:
        print("Positive number")
else:
    print("Negative number")


Enter a number: 08
Positive number


In [12]:
#factorial of a number
fact = 1
i = 1

# To take input from the user
num = int(input("Enter a number: "))

# check if the number is negative or positive
if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
else:
    while i <= num:
        fact = fact*i
        i = i + 1
    print("The factorial of", num, "is", fact)

Enter a number: 46
The factorial of 46 is 5502622159812088949850305428800254892961651752960000000000


In [13]:
#largest among 3 numbers
# Python program to find the largest number among three input numbers
# Change the values of num1, num2, and num3 for a different result

num1 = 10
num2 = 14
num3 = 12

# Uncomment the following lines to take three numbers from user
# num1 = float(input("Enter first number: "))
# num2 = float(input("Enter second number: "))
# num3 = float(input("Enter third number: "))

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number is", largest)


The largest number is 14


In [14]:
#numpy program
import numpy as np

# Create a 2D array with shape (3, 4) filled with ones
array_shape = (3, 4)
ones_array = np.ones(array_shape)

print("Array of ones with shape", array_shape)
print(ones_array)


Array of ones with shape (3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
#2D
import random

N = 5  # Change this to the desired size of your array
random_2d_array = [[random.random() for _ in range(N)] for _ in range(N)]


In [17]:
#linespace to generate array
# Python Programming illustrating
# numpy.linspace method

import numpy as geek

# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")

# To evaluate sin() in long range
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))



B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [18]:
#python program to generate an array of 10 equally spacedvalues between 1 to 100 using linespace
import numpy as geek

# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")

# To evaluate sin() in long range
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))


B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [19]:
#array containing even numbers
import numpy as np

# Create an array of even numbers from 2 to 20
even_numbers = np.arange(2, 21, 2)

print("Array of even numbers:", even_numbers)


Array of even numbers: [ 2  4  6  8 10 12 14 16 18 20]


In [20]:
#to create  an array containing  numbers from 1 to 10  with a step size of 0.5 using range
import numpy as np

# Create an array with values from 1 to 10 (inclusive) and a step size of 0.5
number_array = np.arange(1, 10.5, 0.5).tolist()

print(number_array)



[1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]
